// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: banners/banners.proto

package banners

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// слот ID
type SlotId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SlotId) Reset() {
	*x = SlotId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotId) ProtoMessage() {}

func (x *SlotId) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotId.ProtoReflect.Descriptor instead.
func (*SlotId) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{0}
}

func (x *SlotId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// слот
type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId      int64  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *Slot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

//баннер ID
type BannerId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BannerId) Reset() {
	*x = BannerId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerId) ProtoMessage() {}

func (x *BannerId) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerId.ProtoReflect.Descriptor instead.
func (*BannerId) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{2}
}

func (x *BannerId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// баннер
type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId    int64  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{3}
}

func (x *Banner) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserGroupsId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserGroupsId) Reset() {
	*x = UserGroupsId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupsId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupsId) ProtoMessage() {}

func (x *UserGroupsId) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupsId.ProtoReflect.Descriptor instead.
func (*UserGroupsId) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{4}
}

func (x *UserGroupsId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Соц-дем. группа пользователей
type UserGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGroupsId int64  `protobuf:"varint,1,opt,name=user_groups_id,json=userGroupsId,proto3" json:"user_groups_id,omitempty"`
	Description  string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UserGroups) Reset() {
	*x = UserGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroups) ProtoMessage() {}

func (x *UserGroups) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroups.ProtoReflect.Descriptor instead.
func (*UserGroups) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{5}
}

func (x *UserGroups) GetUserGroupsId() int64 {
	if x != nil {
		return x.UserGroupsId
	}
	return 0
}

func (x *UserGroups) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// слот баннера
type SlotBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId int64 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	SlotId   int64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (x *SlotBanner) Reset() {
	*x = SlotBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotBanner) ProtoMessage() {}

func (x *SlotBanner) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotBanner.ProtoReflect.Descriptor instead.
func (*SlotBanner) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{6}
}

func (x *SlotBanner) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *SlotBanner) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// слот баннера -- not needed
type BannerSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId   int64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BannerId int64 `protobuf:"varint,2,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
}

func (x *BannerSlot) Reset() {
	*x = BannerSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerSlot) ProtoMessage() {}

func (x *BannerSlot) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerSlot.ProtoReflect.Descriptor instead.
func (*BannerSlot) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{7}
}

func (x *BannerSlot) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *BannerSlot) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

type SlotBannerUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotBanner  int64 `protobuf:"varint,1,opt,name=slot_banner,json=slotBanner,proto3" json:"slot_banner,omitempty"`
	UserGroupId int64 `protobuf:"varint,2,opt,name=user_group_id,json=userGroupId,proto3" json:"user_group_id,omitempty"`
}

func (x *SlotBannerUser) Reset() {
	*x = SlotBannerUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotBannerUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotBannerUser) ProtoMessage() {}

func (x *SlotBannerUser) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotBannerUser.ProtoReflect.Descriptor instead.
func (*SlotBannerUser) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{8}
}

func (x *SlotBannerUser) GetSlotBanner() int64 {
	if x != nil {
		return x.SlotBanner
	}
	return 0
}

func (x *SlotBannerUser) GetUserGroupId() int64 {
	if x != nil {
		return x.UserGroupId
	}
	return 0
}

type UserGroupBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotId       int64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	UserGroupsId int64 `protobuf:"varint,2,opt,name=user_groups_id,json=userGroupsId,proto3" json:"user_groups_id,omitempty"`
}

func (x *UserGroupBanner) Reset() {
	*x = UserGroupBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banners_banners_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupBanner) ProtoMessage() {}

func (x *UserGroupBanner) ProtoReflect() protoreflect.Message {
	mi := &file_banners_banners_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupBanner.ProtoReflect.Descriptor instead.
func (*UserGroupBanner) Descriptor() ([]byte, []int) {
	return file_banners_banners_proto_rawDescGZIP(), []int{9}
}

func (x *UserGroupBanner) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *UserGroupBanner) GetUserGroupsId() int64 {
	if x != nil {
		return x.UserGroupsId
	}
	return 0
}

var File_banners_banners_proto protoreflect.FileDescriptor

var file_banners_banners_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a,
	0x06, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x08, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x1e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x54, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x24, 0x0a,
	0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x55, 0x0a,
	0x0e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x22, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x49, 0x64, 0x32, 0xc8, 0x02, 0x0a, 0x07, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x13,
	0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x6c, 0x6f, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x31, 0x12, 0x13,
	0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12,
	0x17, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x11, 0x2e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x79, 0x36, 0x6c, 0x69, 0x6b, 0x2f, 0x6f,
	0x74, 0x75, 0x73, 0x5f, 0x67, 0x6f, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_banners_banners_proto_rawDescOnce sync.Once
	file_banners_banners_proto_rawDescData = file_banners_banners_proto_rawDesc
)

func file_banners_banners_proto_rawDescGZIP() []byte {
	file_banners_banners_proto_rawDescOnce.Do(func() {
		file_banners_banners_proto_rawDescData = protoimpl.X.CompressGZIP(file_banners_banners_proto_rawDescData)
	})
	return file_banners_banners_proto_rawDescData
}

var file_banners_banners_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_banners_banners_proto_goTypes = []interface{}{
	(*SlotId)(nil),          // 0: banners.SlotId
	(*Slot)(nil),            // 1: banners.Slot
	(*BannerId)(nil),        // 2: banners.BannerId
	(*Banner)(nil),          // 3: banners.Banner
	(*UserGroupsId)(nil),    // 4: banners.UserGroupsId
	(*UserGroups)(nil),      // 5: banners.UserGroups
	(*SlotBanner)(nil),      // 6: banners.SlotBanner
	(*BannerSlot)(nil),      // 7: banners.BannerSlot
	(*SlotBannerUser)(nil),  // 8: banners.SlotBannerUser
	(*UserGroupBanner)(nil), // 9: banners.UserGroupBanner
	(*emptypb.Empty)(nil),   // 10: google.protobuf.Empty
}
var file_banners_banners_proto_depIdxs = []int32{
	6,  // 0: banners.Rotator.AddBanner:input_type -> banners.SlotBanner
	7,  // 1: banners.Rotator.RemoveBanner:input_type -> banners.BannerSlot
	6,  // 2: banners.Rotator.RemoveBanner1:input_type -> banners.SlotBanner
	8,  // 3: banners.Rotator.CountLinkClick:input_type -> banners.SlotBannerUser
	9,  // 4: banners.Rotator.SelectBanner:input_type -> banners.UserGroupBanner
	10, // 5: banners.Rotator.AddBanner:output_type -> google.protobuf.Empty
	10, // 6: banners.Rotator.RemoveBanner:output_type -> google.protobuf.Empty
	10, // 7: banners.Rotator.RemoveBanner1:output_type -> google.protobuf.Empty
	10, // 8: banners.Rotator.CountLinkClick:output_type -> google.protobuf.Empty
	2,  // 9: banners.Rotator.SelectBanner:output_type -> banners.BannerId
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_banners_banners_proto_init() }
func file_banners_banners_proto_init() {
	if File_banners_banners_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_banners_banners_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupsId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotBannerUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banners_banners_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_banners_banners_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banners_banners_proto_goTypes,
		DependencyIndexes: file_banners_banners_proto_depIdxs,
		MessageInfos:      file_banners_banners_proto_msgTypes,
	}.Build()
	File_banners_banners_proto = out.File
	file_banners_banners_proto_rawDesc = nil
	file_banners_banners_proto_goTypes = nil
	file_banners_banners_proto_depIdxs = nil
}
